### PR TITLE
taipei-day-trip

### PR DESCRIPTION
**Pull request by wen527555**
何佳玟

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
We should setup protection rule for `main` branch.

**Comment by wen527555** [comment]
> `main`我們應該為分支設置保護規則。

**Comment by wen527555** [comment]
已設定好main分支的保護規則

**Comment by cwpeng** [comment]
Re-request review from reviewers section in the right side of this page if you fix issue.

**Review by cwpeng — APPROVED** [review]
OK. Remember to merge pull request after review approval.

**Pull request merged**
